Update documentation for GameLevel and GameLevelDefaultImpl
Lille1-OpenDevs/lille-game-framework pull request #4
Opened 2017-01-20 13:37 UTC by JoelTroch

##### Opendev - Team n°3
-----

This pull request update the documentation of GameLevel and GameLevelDefaultImpl for better understanding of their purposes.

2017-01-20 15:13 UTC, cdlm requested changes
Comments that paraphrase the code are not helpful; needs more details to be worth merging.

2017-01-20 15:13 UTC, cdlm commented on src/main/java/gameframework/game/GameLevel.java
> + * Interface for game levels.
Useless, this paraphrases the Java declaration.

2017-01-20 15:13 UTC, cdlm commented on src/main/java/gameframework/game/GameLevel.java
> + * Technically speaking, a "GameLevel" is just a thread whose initialize/simulate/free the level.
Please double-check the grammar

- /technically speaking/: says nothing
- /is just a thread/: …so? How is it used in the rest of the framework? Why is a thread needed?

2017-01-20 15:13 UTC, cdlm commented on src/main/java/gameframework/game/GameLevel.java
> +	/** Start the level (aka thread). */
Can you explain when/in which conditions this can/should be used, and what will be the result?

2017-01-27 12:56 UTC, JoelTroch commented
I applied the suggestions above, let us know what you think.

2017-01-27 14:09 UTC, closed without merging

2017-01-27 14:38 UTC, cdlm commented
👍